// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtL6hGe7vaCgZQFVKyukBBlJSxqSoRITo',
    appId: '1:77033369470:web:299b881ad2f399a768cd2f',
    messagingSenderId: '77033369470',
    projectId: 'flutter-easy-card',
    authDomain: 'flutter-easy-card.firebaseapp.com',
    storageBucket: 'flutter-easy-card.appspot.com',
    measurementId: 'G-WP329PYNMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrvH2WiTmKYip-2BUkGT_aQeTwabV0lI',
    appId: '1:77033369470:android:c6c709b21b47cc1168cd2f',
    messagingSenderId: '77033369470',
    projectId: 'flutter-easy-card',
    storageBucket: 'flutter-easy-card.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2eHSYlW48U_MhbAaaRvVGWd2FSfuWVo',
    appId: '1:77033369470:ios:d87ecdd743fa9cc168cd2f',
    messagingSenderId: '77033369470',
    projectId: 'flutter-easy-card',
    storageBucket: 'flutter-easy-card.appspot.com',
    iosClientId:
        '77033369470-1b3trcncf99op9hjrkkmjul4t7gu0i4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEasyCard',
  );
}
